// Code generated by xgen. DO NOT EDIT.

package musicxml

import (
	"encoding/xml"
)

// Lang is Attempting to install the relevant ISO 2- and 3-letter
//          codes as the enumerated possible values is probably never
//          going to be a realistic possibility.  See
//          RFC 3066 at http://www.ietf.org/rfc/rfc3066.txt and the IANA registry
//          at http://www.iana.org/assignments/lang-tag-apps.htm for
//          further information.
//
//          The union allows for the 'un-declaration' of xml:lang with
//          the empty string.
type Lang string

// Space ...
type Space string

// Base is See http://www.w3.org/TR/xmlbase/ for
//                      information about this attribute.
type Base string

// Id is See http://www.w3.org/TR/xml-id/ for
//                      information about this attribute.
type Id string

// SpecialAttrs ...
type SpecialAttrs struct {
	XMLName      xml.Name `xml:"specialAttrs"`
	XmlBaseAttr  string   `xml:"xml:base,attr,omitempty"`
	XmlLangAttr  string   `xml:"xml:lang,attr,omitempty"`
	XmlSpaceAttr string   `xml:"xml:space,attr,omitempty"`
	XmlIdAttr    string   `xml:"xml:id,attr,omitempty"`
}
